// src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // Geistフォントのインポート
import { ModalProvider } from '@/contexts/ModalContext'; // ModalProviderのインポートパスを確認
import NavigationBar from '@/components/modules/NavigationBar'; // NavigationBarのインポートパスを確認
import "./globals.css";

// Geistフォントの設定
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// メタデータの設定
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayoutコンポーネント
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="scroll-smooth">
      <head>
        {/* Adobe Fontsなどの外部フォントシートのリンク */}
        {/* 注意: xxxxxxx の部分は実際のアカウントIDなどに置き換えてください */}
        <link rel="stylesheet" href="https://use.typekit.net/xxxxxxx.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // フォント変数とアンチエイリアスを適用
      >
        {/* ModalProviderでアプリケーションの主要部分をラップ */}
        <ModalProvider>
          {/* NavigationBarをModalProviderの内側に配置 */}
          <NavigationBar />
          {/* page.tsxなどの子コンポーネントがここにレンダリングされる */}
          <main>{children}</main>
          {/* Footerなどの他の共通レイアウトコンポーネントもModalProviderの内側に配置可能 */}
        </ModalProvider>
      </body>
    </html>
  );
}
